global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Query;
global using Simulator.Server.Interfaces.EndPoints;
global using Simulator.Server.Repositories;
global using Simulator.Shared.Commons;
global using Simulator.Shared.StaticClasses;
global using System.Linq.Expressions;
global using UnitSystem;
global using QWENShared.DTOS.Base;
